export const projects = [
  {
    url: "https://www.kncelados.com",
    title: "Kncelados Podcast",
    description: "Pagina web oficial para el podcast de Kncelados. Uso de scrappers e inteligencia artificial para generar el contenido.",
    image: "https://www.kncelados.com/favicon.svg",
    technologies: ["astro", "tailwind"],
    github: "https://github.com/verdulife/kncelados-web",
  },
  {
    url: "https://www.calandraautomobili.com",
    title: "Calandra Automovili",
    description: "Pagina web de Calandra, una marca de automóviles de Barcelona.",
    image: "https://www.calandraautomobili.com/favicon.svg",
    technologies: ["astro", "tailwind"],
    github: "https://github.com/verdulife/calandra-automobili",
  },
  {
    url: "https://ulavet.netlify.app",
    title: "Ulavet Veterinaria",
    description: "Pagina web de Ulavet, una veterinaria en Sant Pere de Ribes. Uso de scrappers para la galeria de instagran",
    image: "https://ulavet.netlify.app/favicon.svg",
    technologies: ["astro", "tailwind"],
    github: "https://github.com/verdulife/ulavet",
  },
  {
    url: "https://www.jardinerialamediterrania.com",
    title: "Jardinería La Medeterránia",
    description: "Pagina web de Jardinería La Medeterránea, una empresa de jardinería en Barcelona. Uso de scrappers para la galeria de instagran",
    image: "https://www.jardinerialamediterrania.com/favicon.svg",
    technologies: ["astro", "tailwind"],
    github: "https://github.com/verdulife/jardinerialamediterrania",
  },
  {
    url: "https://testing.gaplogic.com",
    title: "Gaplogic",
    description: "Pagina web de Gaplogic, una empresa de marketing digital en Sitges.",
    image: "https://testing.gaplogic.com/favicon.svg",
    technologies: ["wordpress", "divi"],
    github: null,
  },
  {
    url: "https://gaudiobarcelona.com",
    title: "Gaudio Art",
    description: "Pagina web de Gaudio Barcelona, una empresa de regalos de arte para empresas en Barcelona.",
    image: "https://gaudiobarcelona.com/favicon.svg",
    technologies: ["wordpress", "divi"],
    github: null,
  },
  {
    url: "https://byebyedespedidas.com",
    title: "Bye Bye Despedidas",
    description: "Pagina web de Bye Bye Despedidas, una empresa de de actividades para despedidas de solteros en Barcelona.",
    image: "https://byebyedespedidas.com/favicon.svg",
    technologies: ["wordpress", "divi"],
    github: null,
  },
  {
    url: "https://stopperinternational.com",
    title: "Stopper Internacional",
    description: "Pagina web de Stopper Internacional, una empresa de agentes de futbol en España.",
    image: "https://stopperinternational.com/favicon.svg",
    technologies: ["wordpress", "divi"],
    github: null,
  },
  {
    url: "https://tattoo-killer.netlify.app",
    title: "Tattoo Killer",
    description: "Pagina web de Tattoo Killer, una empresa de eliminacion detatuajes en Cataluña.",
    image: "https://tattoo-killer.netlify.app/favicon.svg",
    technologies: ["astro", "tailwind"],
    github: null,
  },
  {
    url: "https://www.reggimarengo.com",
    title: "Reggi Marengo",
    description: "Pagina web de Reggi Marengo, una inmobiliaria en Barcelona.",
    image: "https://www.reggimarengo.com/favicon.svg",
    technologies: ["astro", "tailwind"],
    github: null,
  },
  {
    url: "https://menuplis.netlify.app",
    title: "Menuplis",
    description: "Pagina web de Menuplis, web app para la gestión de menús y cartas de restaurantes. Creacion de pagina web, CRM para restaurantes y web app para usuario final.",
    image: "https://menuplis.netlify.app/favicon.svg",
    technologies: ["angular", "scss", "firebase"],
    github: "https://github.com/verdulife/menuplis",
  },
  /* "https://www.sitgesgi.com",
  "https://facturasgratis-v2.vercel.app",
  "https://timer-app-seven.vercel.app",
  "https://venarima.vercel.app",
  "https://www.grandefronteo.com",
  "https://gimg-verdulife.vercel.app",
  "https://www.simplementewear.com",
  "https://onedaydesign.vercel.app",
  "https://bleed-two.vercel.app",
  "https://wwwrap.dev", */
]